const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

const FETCH_NPA_PENDING = 'FETCH_NPA_PENDING';
const FETCH_NPA_SUCCESS = 'FETCH_NPA_SUCCESS';
const FETCH_NPA_FAILED = 'FETCH_NPA_FAILED';

const FETCH_ADDRESS_PENDING = 'FETCH_ADDRESS_PENDING';
const FETCH_ADDRESS_SUCCESS = 'FETCH_ADDRESS_SUCCESS';
const FETCH_ADDRESS_FAILED = 'FETCH_ADDRESS_FAILED';

export {CHANGE_SEARCH_FIELD,
    FETCH_NPA_PENDING, FETCH_NPA_SUCCESS, FETCH_NPA_FAILED,
    FETCH_ADDRESS_PENDING, FETCH_ADDRESS_SUCCESS, FETCH_ADDRESS_FAILED
};